kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  labels:
    app: bdp-data-service
  name: bdp-data-service
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bdp-data-service
  template:
    metadata:
      labels:
        app: bdp-data-service
    spec:
      containers:
      - name: bdp-data-service
        image: 192.168.31.72:5000/bdp-data-service:version	
        ports:
        - containerPort: 9876
          protocol: TCP
        volumeMounts: 
            - name: timezone-pv 
              mountPath: /etc/timezone
            - name: localtime-pv 
              mountPath: /etc/localtime
      volumes:
        - name: timezone-pv
          hostPath:
           path: /usr/share/zoneinfo/Asia/Shanghai
        - name: localtime-pv
          hostPath:
           path: /etc/localtime
---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: bdp-data-service
  name: bdp-data-service
  namespace: test
spec:
  type: NodePort
  ports:
  - port: 9876
    targetPort: 9876
    nodePort: 30302
  selector:
    app: bdp-data-service