kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  labels:
    app: bdp-authorization-service
  name: bdp-authorization-service
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bdp-authorization-service
  template:
    metadata:
      labels:
        app: bdp-authorization-service
    spec:
      containers:
      - name: bdp-authorization-service
        image: 192.168.31.72:5000/bdp-authorization-service:version	
        ports:
        - containerPort: 9797
          protocol: TCP
        volumeMounts: 
            - name: timezone-pv 
              mountPath: /etc/timezone
            - name: localtime-pv 
              mountPath: /etc/localtime
      volumes:
        - name: timezone-pv
          hostPath:
           path: /usr/share/zoneinfo/Asia/Shanghai
        - name: localtime-pv
          hostPath:
           path: /etc/localtime
---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: bdp-authorization-service
  name: bdp-authorization-service
  namespace: test
spec:
  type: NodePort
  ports:
  - port: 9797
    targetPort: 9797
    nodePort: 30304
  selector:
    app: bdp-authorization-service